version: '3.8'

services:
  web:
    container_name: web
    build: ./docker/web
    ports:
      - 9000:9000
    privileged: true
    volumes:
      - ./server:/app:cached
      - /app/node_modules
    tty: true
    stdin_open: true
    command: /bin/sh
    